<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<RootNamespace>StudioOMS</RootNamespace>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<PublishAot>false</PublishAot>
		<RunAOTCompilation>false</RunAOTCompilation>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StudioOMS.WebApi.Sdk\StudioOMS.WebApi.Sdk.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Pages\Admin\" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="StudioOMS.UnitTests" />
	</ItemGroup>


</Project>
