<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<PublishAot>false</PublishAot>
		<RunAOTCompilation>false</RunAOTCompilation>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\StudioOMS.Dtos\StudioOMS.Dtos.csproj" />
	</ItemGroup>

</Project>
