<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>StudioOMS</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\StudioOMS.Dtos\StudioOMS.Dtos.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="StudioOMS.UnitTests" />
	</ItemGroup>


</Project>
