<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>StudioOMS</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Http" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StudioOMS.Dtos\StudioOMS.Dtos.csproj" />
		<ProjectReference Include="..\StudioOMS.ErrorCodes\StudioOMS.WebApi.Response.csproj" />
		<ProjectReference Include="..\StudioOMS.WebApi.Routes\StudioOMS.WebApi.Routes.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="StudioOMS.UnitTests" />
	</ItemGroup>

</Project>
