// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioOMS.EfCore;

#nullable disable

namespace StudioOMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920104847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StudioOMS.Clients.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("StudioOMS.Employees.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("StudioOMS.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedEmployees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalespersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SalespersonId");

                    b.ToTable("Order", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StudioOMS.Orders.OrderConsume", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Order.Consume", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("OrderConsume");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudioOMS.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("StudioOMS.Orders.Timing.TimingOrder", b =>
                {
                    b.HasBaseType("StudioOMS.Orders.Order");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("TEXT");

                    b.ToTable("Order.Timing", (string)null);
                });

            modelBuilder.Entity("StudioOMS.Orders.Timing.TimingOrderConsume", b =>
                {
                    b.HasBaseType("StudioOMS.Orders.OrderConsume");

                    b.Property<decimal>("Days")
                        .HasColumnType("TEXT");

                    b.HasIndex("OrderId");

                    b.HasDiscriminator().HasValue("TimingOrderConsume");
                });

            modelBuilder.Entity("StudioOMS.Orders.Order", b =>
                {
                    b.HasOne("StudioOMS.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioOMS.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("SalespersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioOMS.Orders.OrderConsume", b =>
                {
                    b.HasOne("StudioOMS.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioOMS.Users.User", b =>
                {
                    b.HasOne("StudioOMS.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioOMS.Orders.Timing.TimingOrder", b =>
                {
                    b.HasOne("StudioOMS.Orders.Order", null)
                        .WithOne()
                        .HasForeignKey("StudioOMS.Orders.Timing.TimingOrder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioOMS.Orders.Timing.TimingOrderConsume", b =>
                {
                    b.HasOne("StudioOMS.Orders.Timing.TimingOrder", null)
                        .WithMany("Consumes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StudioOMS.Orders.Timing.TimingOrder", b =>
                {
                    b.Navigation("Consumes");
                });
#pragma warning restore 612, 618
        }
    }
}
