<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<RootNamespace>StudioOMS</RootNamespace>
		<EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
		<PublishAot>false</PublishAot>
		<IsAotCompatible>false</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StudioOMS.Dtos\StudioOMS.Dtos.csproj" />
		<ProjectReference Include="..\StudioOMS.Infrastructure\StudioOMS.Infrastructure.csproj" />
	</ItemGroup>

</Project>
