<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
		<PublishAot>false</PublishAot>
		<IsAotCompatible>false</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StudioOMS.Infrastructure\StudioOMS.Infrastructure.csproj" />
		<ProjectReference Include="..\StudioOMS.Dtos\StudioOMS.Dtos.csproj" />
		<ProjectReference Include="..\StudioOMS.WebApi.Routes\StudioOMS.WebApi.Routes.csproj" />
		<ProjectReference Include="..\StudioOMS.WebApi.Response\StudioOMS.WebApi.Response.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="StudioOMS.UnitTests" />
	</ItemGroup>


</Project>
