<Project>

	<!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
	<PropertyGroup>

		<!--版本-->
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>preview</LangVersion>

		<!--特性-->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

	</PropertyGroup>

	<!--调试文件-->
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>


	<!--.net8 Aot-->
	<!--<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">-->
	<!--<PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals('$(TargetFrameworkVersion)', 'net8.0'))">-->
	<!--<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0' OR '$(TargetFramework)' == 'net11.0'">-->
	<PropertyGroup>

		<!-- 开启 AOT 发布 -->
		<PublishAot>true</PublishAot>
		<!-- 声明与 AOT 兼容 -->
		<IsAotCompatible>true</IsAotCompatible>
		<!-- 检查引用的库是否与 AOT 兼容 -->
		<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>

		<!-- AOT 优化选项 -->
		<!-- partial: 尽可能剪裁，但保留可能通过反射使用的代码 -->
		<TrimMode>partial</TrimMode>
		<!-- 全球化不变模式，可减小体积，但确保你的应用不需要特定文化信息 -->
		<InvariantGlobalization>true</InvariantGlobalization>
		<!-- AOT 编译器优化偏好：Size 或 Speed -->
		<IlcOptimizationPreference>Size</IlcOptimizationPreference>
		<!-- 合并相同的方法体以减小体积 -->
		<IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
		<!-- JIT 编译器优化偏好：此处为 Speed -->
		<OptimizationPreference>Speed</OptimizationPreference>

	</PropertyGroup>

</Project>